import React from 'react';
import TaskComponent from './TaskComponent';
import { TaskIcon, SparklesIcon, TrashIcon, DownloadIcon } from './Icons';

const RoadmapView = ({ goals, allTasks, openEditModal, handleDeleteTask, handleDeleteGoal, fetchData }) => {
  const exportGoalToMarkdown = (goal) => {
    const sortedGoalTasks = [...(goal.tasks || [])].sort((a, b) => new Date(a.date) - new Date(b.date));
    
    let md = `# Goal: ${goal.title}\n\n`;
    md += `> ${goal.description || 'No description provided.'}\n\n`;
    md += `## Execution Roadmap\n\n`;
    
    if (sortedGoalTasks.length === 0) {
      md += `*No tasks added to this roadmap yet.*\n`;
    } else {
      sortedGoalTasks.forEach((task, index) => {
        const status = task.status === 'done' ? 'x' : ' ';
        md += `### ${index + 1}. ${task.title}\n`;
        md += `- [${status}] **Status:** ${task.status.toUpperCase()}\n`;
        md += `- 📅 **Date:** ${task.date || 'TBD'}\n`;
        md += `- ⏱️ **Duration:** ${task.duration_minutes} mins\n`;
        if (task.description) {
          md += `\n**Description:**\n${task.description}\n`;
        }
        md += `\n---\n\n`;
      });
    }
    
    md += `\n*Generated by Nexora AI Strategy Engine on ${new Date().toLocaleDateString()}*`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Nexora_Roadmap_${goal.title.replace(/\s+/g, '_')}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-12">
      {/* Roadmap View: Grouped by Goals */}
      {goals.sort((a,b) => new Date(b.created_at) - new Date(a.created_at)).map((goal) => (
        <div key={goal.id} className="space-y-6">
          <div className="flex items-center justify-between group">
            <div className="flex items-center gap-4">
              <div className="p-3 bg-purple-500/10 rounded-2xl border border-purple-500/20">
                <SparklesIcon className="w-6 h-6 text-purple-400" />
              </div>
              <div>
                <h2 className="text-xl font-bold text-white leading-tight">{goal.title}</h2>
                <p className="text-xs text-slate-500 font-medium">Goal Roadmap • {(goal.tasks || []).length} Steps</p>
              </div>
            </div>
            <div className="flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-all">
              <button 
                onClick={() => exportGoalToMarkdown(goal)}
                className="p-2 text-slate-500 hover:text-cyan-400 hover:bg-cyan-400/10 rounded-lg transition-all"
                title="Export Markdown"
              >
                <DownloadIcon className="w-4 h-4" />
              </button>
              <button 
                onClick={() => handleDeleteGoal(goal.id)}
                className="p-2 text-slate-500 hover:text-rose-400 hover:bg-rose-400/10 rounded-lg transition-all"
                title="Delete Goal"
              >
                <TrashIcon className="w-4 h-4" />
              </button>
            </div>
          </div>
          
          <div className="relative pl-8 space-y-4 before:absolute before:left-[23px] before:top-2 before:bottom-2 before:w-[2px] before:bg-slate-800/60">
            {(goal.tasks || []).sort((a,b) => new Date(a.date) - new Date(b.date)).map((task) => (
              <div key={task.id} className="relative">
                <div className="absolute -left-[14px] top-1/2 -translate-y-1/2 w-2 h-2 rounded-full bg-slate-700 border border-[#0f172a] z-10"></div>
                <TaskComponent 
                  task={task} 
                  onEdit={() => openEditModal(task)}
                  onDelete={() => handleDeleteTask(task.id)}
                  onUpdate={fetchData}
                />
              </div>
            ))}
          </div>
        </div>
      ))}

      {/* Standalone Tasks in Roadmap View */}
      {allTasks.filter(t => !t.goal_id).length > 0 && (
        <div className="space-y-6">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-slate-800/50 rounded-2xl border border-slate-700">
              <TaskIcon className="w-6 h-6 text-slate-400" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white leading-tight">Standalone Tasks</h2>
              <p className="text-xs text-slate-500 font-medium">Individual actions without a specific goal</p>
            </div>
          </div>
          <div className="grid gap-4">
            {allTasks.filter(t => !t.goal_id).sort((a,b) => new Date(a.date) - new Date(b.date)).map((task) => (
              <TaskComponent 
                key={task.id} 
                task={task} 
                onEdit={() => openEditModal(task)}
                onDelete={() => handleDeleteTask(task.id)}
                onUpdate={fetchData}
              />
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default RoadmapView;